apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: springbootdemo
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Project=springbootdemo
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: springbootdemo
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: springbootdemo
spec:
  type: LoadBalancer
  selector:
    app: springbootdemo
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdemo
  labels:
    app: springbootdemo
  namespace: default
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: springbootdemo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: springbootdemo
    spec:
      containers:
      - image: {ecr_image}
        imagePullPolicy: Always
        name: springbootdemo
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: node
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName