apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-graviton
spec:
  selector:
    matchLabels:
      app:  hello-graviton
  replicas: 0
  template:
    metadata:
      labels:
        app: hello-graviton
    spec:
      containers:
      - name: hello-graviton
        image: 704533066374.dkr.ecr.eu-west-1.amazonaws.com/graviton-multi-arch-pipeline:latest
