apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-graviton
spec:
  selector:
    matchLabels:
      app:  hello-graviton
  replicas: 0
  template:
    metadata:
      labels:
        app: hello-graviton
    spec:
      containers:
      - name: hello-graviton
        image: {aws account}.dkr.ecr.{region}.amazonaws.com/{ecr image -e.g demo-graviton-multi-arch:latest}
